import { Category, Product } from "./types";

export const categories: Category[] = [
  { id: 'fans', name: 'Fans', slug: 'fans', description: 'Latest gadgets and devices', image: '/images/fans.jpeg' },
  { id: 'switchesandsockets', name: 'Switches and Sockets', slug: 'switches-and-sockets', description: 'Trendy clothing and accessories', image: '/images/switches.jpeg' },
  { id: 'ledlights', name: 'Led Lights', slug: 'ledlights', description: 'Everything for your home', image: '/images/bulbs.jpeg' },
  { id: 'cablesandwires', name: 'Cables and Wires', slug: 'cables-and-wires', description: 'Equipment and gear for active lifestyles', image: '/images/wires.jpeg' },
];

export const products: Product[] = [
  {
    id: 'p1sdsd',
    name: 'smart electrice remote fan',
    description: 'Smart electric remote controlled fan with multiple speed settings',
    price: 199.99,
    salePrice: 149.99,
    image: '/images/fans.jpeg',
    category: 'fans',
    isFeatured: true,
    quantity: 35,
    closeOut: false,
    createdAt: '2025-01-10',
  },
  {
    id: 'p2',
    name: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker with deep bass',
    price: 89.99,
    salePrice: 69.99,
    image: '/images/speaker.jpg',
    category: 'electronics',
    isFeatured: false,
    quantity: 60,
    closeOut: false,
  },
  {
    id: 'p3',
    name: 'Smart Watch',
    description: 'Fitness tracking smart watch with heart rate monitor',
    price: 249.99,
    salePrice: 199.99,
    image: '/images/smartwatch.jpg',
    category: 'electronics',
    isFeatured: true,
    quantity: 25,
    closeOut: false,
  },
  {
    id: 'p4',
    name: 'Gaming Mouse',
    description: 'High precision RGB gaming mouse',
    price: 59.99,
    salePrice: 39.99,
    image: '/images/mouse.jpg',
    category: 'electronics',
    isFeatured: false,
    quantity: 80,
    closeOut: false,
  },
  {
    id: 'p5',
    name: 'Mechanical Keyboard',
    description: 'Mechanical keyboard with blue switches',
    price: 129.99,
    salePrice: 99.99,
    image: '/images/keyboard.jpg',
    category: 'electronics',
    isFeatured: true,
    quantity: 40,
    closeOut: false,
  },

  {
    id: 'p6',
    name: 'Running Shoes',
    description: 'Lightweight running shoes for daily training',
    price: 119.99,
    salePrice: 89.99,
    image: '/images/shoes.jpg',
    category: 'fashion',
    isFeatured: true,
    quantity: 50,
    closeOut: false,
  },
  {
    id: 'p7',
    name: 'Leather Jacket',
    description: 'Genuine leather biker jacket',
    price: 299.99,
    salePrice: 249.99,
    image: '/images/jacket.jpg',
    category: 'fashion',
    isFeatured: false,
    quantity: 15,
    closeOut: false,
  },
  {
    id: 'p8',
    name: 'Casual T-Shirt',
    description: '100% cotton casual t-shirt',
    price: 29.99,
    salePrice: 19.99,
    image: '/images/tshirt.jpg',
    category: 'fashion',
    isFeatured: false,
    quantity: 120,
    closeOut: false,
  },
  {
    id: 'p9',
    name: 'Denim Jeans',
    description: 'Slim fit denim jeans',
    price: 79.99,
    salePrice: 59.99,
    image: '/images/jeans.jpg',
    category: 'fashion',
    isFeatured: true,
    quantity: 70,
    closeOut: false,
  },
  {
    id: 'p10',
    name: 'Baseball Cap',
    description: 'Adjustable cotton baseball cap',
    price: 24.99,
    salePrice: 14.99,
    image: '/images/cap.jpg',
    category: 'fashion',
    isFeatured: false,
    quantity: 150,
    closeOut: true,
  },

  {
    id: 'p11',
    name: 'Coffee Maker',
    description: 'Automatic drip coffee maker',
    price: 149.99,
    salePrice: 119.99,
    image: '/images/coffeemaker.jpg',
    category: 'home',
    isFeatured: true,
    quantity: 30,
    closeOut: false,
  },
  {
    id: 'p12',
    name: 'Vacuum Cleaner',
    description: 'High suction bagless vacuum cleaner',
    price: 229.99,
    salePrice: 189.99,
    image: '/images/vacuum.jpg',
    category: 'home',
    isFeatured: false,
    quantity: 20,
    closeOut: false,
  },
  {
    id: 'p13',
    name: 'Air Fryer',
    description: 'Oil-free digital air fryer',
    price: 179.99,
    salePrice: 139.99,
    image: '/images/airfryer.jpg',
    category: 'home',
    isFeatured: true,
    quantity: 45,
    closeOut: false,
  },
  {
    id: 'p14',
    name: 'Blender',
    description: 'High-speed kitchen blender',
    price: 99.99,
    salePrice: 79.99,
    image: '/images/blender.jpg',
    category: 'home',
    isFeatured: false,
    quantity: 55,
    closeOut: false,
  },
  {
    id: 'p15',
    name: 'Desk Lamp',
    description: 'LED desk lamp with adjustable brightness',
    price: 49.99,
    salePrice: 29.99,
    image: '/images/lamps.jpg',
    category: 'home',
    isFeatured: true,
    quantity: 90,
    closeOut: true,
  },

  {
    id: 'p16',
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat',
    price: 39.99,
    salePrice: 24.99,
    image: '/images/yogamat.jpg',
    category: 'fitness',
    isFeatured: true,
    quantity: 100,
    closeOut: false,
  },
  {
    id: 'p17',
    name: 'Dumbbell Set',
    description: 'Adjustable dumbbell set',
    price: 199.99,
    salePrice: 159.99,
    image: '/images/dumbbells.jpg',
    category: 'fitness',
    isFeatured: false,
    quantity: 25,
    closeOut: false,
  },
  {
    id: 'p18',
    name: 'Resistance Bands',
    description: 'Set of resistance bands for workouts',
    price: 29.99,
    salePrice: 19.99,
    image: '/images/bands.jpg',
    category: 'fitness',
    isFeatured: false,
    quantity: 140,
    closeOut: false,
  },
  {
    id: 'p19',
    name: 'Treadmill',
    description: 'Foldable electric treadmill',
    price: 899.99,
    salePrice: 749.99,
    image: '/images/treadmill.jpg',
    category: 'fitness',
    isFeatured: true,
    quantity: 10,
    closeOut: false,
  },
  {
    id: 'p20',
    name: 'Foam Roller',
    description: 'Muscle recovery foam roller',
    price: 34.99,
    salePrice: 24.99,
    image: '/images/foamroller.jpg',
    category: 'fitness',
    isFeatured: false,
    quantity: 85,
    closeOut: true,
  },
]

export const featured: Product[] = products.filter(p => p.isFeatured);